### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by Xyaren** [ogrady/ts-gw2-verifyBot#7]
Improve logging issues by using a proper logging implementation

**Comment by ogrady** [comment]
New logging method has been introduced to specify a logging level and give some proper context in https://github.com/ogrady/ts-gw2-verifyBot/commit/04cd9141ebca9cf09f08938832fe2fad72c77a66

See https://github.com/ogrady/ts-gw2-verifyBot/commit/11d6114d5de1ed89d29691e997274231baa8fae4 to learn about the usage

@Jeybla you can now introduce as much additional logging as needed.
